//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domiva.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DomivaEntities : DbContext
    {
        public DomivaEntities()
            : base("name=DomivaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<afp> afp { get; set; }
        public virtual DbSet<Ambulancia> Ambulancia { get; set; }
        public virtual DbSet<ambulancia_estado> ambulancia_estado { get; set; }
        public virtual DbSet<Ambulancia_tipo> Ambulancia_tipo { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<centro_asistencial> centro_asistencial { get; set; }
        public virtual DbSet<Chofer_ambulancia> Chofer_ambulancia { get; set; }
        public virtual DbSet<Choferes> Choferes { get; set; }
        public virtual DbSet<estado> estado { get; set; }
        public virtual DbSet<estado_ambulancia> estado_ambulancia { get; set; }
        public virtual DbSet<insumos> insumos { get; set; }
        public virtual DbSet<insumos_ambulancia> insumos_ambulancia { get; set; }
        public virtual DbSet<persona_centro> persona_centro { get; set; }
        public virtual DbSet<Personal> Personal { get; set; }
        public virtual DbSet<personal_ambulancia> personal_ambulancia { get; set; }
        public virtual DbSet<personal_correo> personal_correo { get; set; }
        public virtual DbSet<Personas> Personas { get; set; }
        public virtual DbSet<salud> salud { get; set; }
        public virtual DbSet<Solicitud_ambulancia> Solicitud_ambulancia { get; set; }
        public virtual DbSet<Solicitud_estado> Solicitud_estado { get; set; }
        public virtual DbSet<Solicitudes> Solicitudes { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<turno> turno { get; set; }
        public virtual DbSet<turno_chofer> turno_chofer { get; set; }
        public virtual DbSet<turno_personal> turno_personal { get; set; }
    }
}
