//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal_ambulancia
    {
        public int id_p_a { get; set; }
        public Nullable<int> id_ambulancia { get; set; }
        public Nullable<int> id_personal { get; set; }
    
        public virtual Ambulancia Ambulancia { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
