//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class persona_centro
    {
        public int id_p_c { get; set; }
        public Nullable<int> id_persona { get; set; }
        public Nullable<int> id_centro { get; set; }
    }
}
