//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class personal_correo
    {
        public int id_p_co { get; set; }
        public Nullable<int> id_personal { get; set; }
        public string id { get; set; }
    
        public virtual AspNetUsers AspNetUsers { get; set; }
        public virtual Personal Personal { get; set; }
    }
}
