//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Personal()
        {
            this.personal_ambulancia = new HashSet<personal_ambulancia>();
            this.personal_correo = new HashSet<personal_correo>();
            this.turno_personal = new HashSet<turno_personal>();
        }
    
        public int Id_personal { get; set; }
        public string Rut_personal { get; set; }
        public string Nombre_personal { get; set; }
        public string Apellido_perso { get; set; }
        public int numero_telefonico { get; set; }
        public string direccion { get; set; }
        public Nullable<int> afp { get; set; }
        public Nullable<int> salud { get; set; }
        public string id_rol { get; set; }
        public Nullable<int> id_centro { get; set; }
    
        public virtual afp afp1 { get; set; }
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual centro_asistencial centro_asistencial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personal_ambulancia> personal_ambulancia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<personal_correo> personal_correo { get; set; }
        public virtual salud salud1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<turno_personal> turno_personal { get; set; }
    }
}
