//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Domiva.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class turno_chofer
    {
        public int id_turno_chofer { get; set; }
        public Nullable<int> id_turno { get; set; }
        public Nullable<int> id_chofer { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
    
        public virtual Choferes Choferes { get; set; }
        public virtual turno turno { get; set; }
    }
}
